"""
Horizon Theme Environment for Coding Agent RL.

Task: Generate Shopify page templates (JSON) based on the Horizon theme.
Validation: JSON syntax + section/block reference check + shopify theme check.
"""

import json
import os
import subprocess
import tempfile
import shutil
from pathlib import Path
from dataclasses import dataclass


@dataclass
class ValidationResult:
    """Result of validating a generated template."""
    json_valid: bool = False
    json_error: str = ""
    sections_valid: bool = False
    sections_error: str = ""
    theme_check_valid: bool = False
    theme_check_output: str = ""
    theme_check_errors: list = None

    def __post_init__(self):
        if self.theme_check_errors is None:
            self.theme_check_errors = []

    @property
    def all_passed(self) -> bool:
        return self.json_valid and self.sections_valid and self.theme_check_valid

    def to_reward_dict(self) -> dict[str, float]:
        """Return binary rewards for each check."""
        return {
            "json_valid": 1.0 if self.json_valid else 0.0,
            "sections_valid": 1.0 if self.sections_valid else 0.0,
            "theme_check_valid": 1.0 if self.theme_check_valid else 0.0,
        }

    def get_error_message(self) -> str:
        """Return first error message for OPD hint extraction."""
        if not self.json_valid:
            return f"JSON Error: {self.json_error}"
        if not self.sections_valid:
            return f"Section Error: {self.sections_error}"
        if not self.theme_check_valid and self.theme_check_errors:
            return f"Theme Check: {self.theme_check_errors[0]}"
        return ""


class HorizonEnvironment:
    """
    Environment that validates generated Shopify templates against the Horizon theme.

    Usage:
        env = HorizonEnvironment("/path/to/horizon")
        result = env.validate("collection", generated_json_string)
    """

    # Valid template types in Horizon
    TEMPLATE_TYPES = [
        "index", "collection", "product", "blog", "article",
        "cart", "search", "page", "page.contact", "list-collections",
        "password", "404",
    ]

    def __init__(self, horizon_path: str):
        self.horizon_path = Path(horizon_path)
        if not (self.horizon_path / "sections").exists():
            raise ValueError(f"Invalid Horizon path: {horizon_path}")

        # Cache available sections and blocks
        self.available_sections = self._scan_dir("sections")
        self.available_blocks = self._scan_dir("blocks")
        self.available_snippets = self._scan_dir("snippets")

    def _scan_dir(self, dirname: str) -> set[str]:
        """Scan a directory for available .liquid file names (without extension)."""
        dirpath = self.horizon_path / dirname
        if not dirpath.exists():
            return set()
        return {
            f.stem.lstrip("_")
            for f in dirpath.iterdir()
            if f.suffix == ".liquid"
        }

    def validate(self, template_type: str, generated_json: str) -> ValidationResult:
        """
        Validate a generated template JSON string.

        Args:
            template_type: e.g. "collection", "product", "page.contact"
            generated_json: The JSON string generated by the model

        Returns:
            ValidationResult with binary pass/fail for each check
        """
        result = ValidationResult()

        # Step 1: JSON syntax check
        try:
            data = self._parse_json(generated_json)
            result.json_valid = True
        except (json.JSONDecodeError, ValueError) as e:
            result.json_error = str(e)
            return result

        # Step 2: Section/block reference check
        section_result = self._check_references(data)
        result.sections_valid = section_result[0]
        result.sections_error = section_result[1]
        if not result.sections_valid:
            return result

        # Step 3: Theme check (requires writing to filesystem)
        tc_result = self._run_theme_check(template_type, generated_json)
        result.theme_check_valid = tc_result[0]
        result.theme_check_output = tc_result[1]
        result.theme_check_errors = tc_result[2]

        return result

    def _parse_json(self, json_str: str) -> dict:
        """Parse and validate basic JSON structure."""
        # Strip leading comments (Horizon templates have auto-generated comments)
        lines = json_str.strip().split("\n")
        json_lines = []
        in_json = False
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("{") or stripped.startswith("["):
                in_json = True
            if in_json:
                json_lines.append(line)

        if not json_lines:
            # Try parsing the whole thing
            data = json.loads(json_str)
        else:
            data = json.loads("\n".join(json_lines))

        # Must have "sections" and "order" keys
        if not isinstance(data, dict):
            raise ValueError("Template must be a JSON object")
        if "sections" not in data:
            raise ValueError("Template must have a 'sections' key")
        if "order" not in data:
            raise ValueError("Template must have an 'order' key")

        return data

    def _check_references(self, data: dict) -> tuple[bool, str]:
        """Check that all referenced sections and block types exist in Horizon."""
        sections = data.get("sections", {})

        for section_key, section_data in sections.items():
            if not isinstance(section_data, dict):
                return False, f"Section '{section_key}' must be an object"

            section_type = section_data.get("type", "")
            if not section_type:
                return False, f"Section '{section_key}' missing 'type' field"

            # Check section type exists
            # Remove "main-" prefix for main sections
            check_type = section_type
            if check_type not in self.available_sections:
                return False, f"Unknown section type '{section_type}'. Available: {sorted(self.available_sections)[:10]}..."

            # Check block types
            blocks = section_data.get("blocks", {})
            for block_key, block_data in blocks.items():
                if not isinstance(block_data, dict):
                    continue
                block_type = block_data.get("type", "")
                if block_type and block_type not in self.available_blocks:
                    # Some block types are inline (text, button, etc.)
                    # Only warn for clearly wrong types
                    pass  # Be lenient on block types for now

        return True, ""

    def _run_theme_check(
        self, template_type: str, generated_json: str
    ) -> tuple[bool, str, list[str]]:
        """Run shopify theme check on the generated template."""
        # Create a temporary copy of Horizon with the generated template
        with tempfile.TemporaryDirectory() as tmpdir:
            # Copy Horizon theme
            shutil.copytree(self.horizon_path, f"{tmpdir}/theme", dirs_exist_ok=True)

            # Write generated template
            template_filename = f"{template_type}.json"
            template_path = Path(tmpdir) / "theme" / "templates" / template_filename
            template_path.write_text(generated_json)

            # Run theme check
            try:
                proc = subprocess.run(
                    ["shopify", "theme", "check", "--path", f"{tmpdir}/theme",
                     "--fail-level", "error"],
                    capture_output=True,
                    text=True,
                    timeout=30,
                    cwd=tmpdir,
                )
                output = proc.stdout + proc.stderr
                errors = self._parse_theme_check_errors(output, template_filename)
                passed = proc.returncode == 0 or len(errors) == 0
                return passed, output, errors
            except subprocess.TimeoutExpired:
                return False, "Theme check timed out", ["Timeout after 30s"]
            except FileNotFoundError:
                # shopify CLI not installed — skip this check
                return True, "shopify CLI not available, skipping", []

    def _parse_theme_check_errors(self, output: str, template_filename: str) -> list[str]:
        """Parse theme check output for errors related to our template."""
        errors = []
        lines = output.split("\n")
        capture = False
        current_error = []

        for line in lines:
            if template_filename in line:
                capture = True
                current_error = [line]
            elif capture:
                if line.strip() == "" or line.startswith("╭") or line.startswith("╰"):
                    if current_error:
                        errors.append("\n".join(current_error))
                        current_error = []
                    if line.startswith("╰"):
                        capture = False
                else:
                    current_error.append(line)

        if current_error:
            errors.append("\n".join(current_error))

        return errors

    def get_ground_truth(self, template_type: str) -> str | None:
        """Load the original Horizon template as ground truth."""
        template_path = self.horizon_path / "templates" / f"{template_type}.json"
        if template_path.exists():
            return template_path.read_text()
        return None

    def list_templates(self) -> list[str]:
        """List all available template types."""
        templates_dir = self.horizon_path / "templates"
        return [
            f.stem
            for f in templates_dir.iterdir()
            if f.suffix == ".json"
        ]


if __name__ == "__main__":
    # Quick test
    import sys

    horizon_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/horizon"

    env = HorizonEnvironment(horizon_path)
    print(f"Sections: {len(env.available_sections)}")
    print(f"Blocks: {len(env.available_blocks)}")
    print(f"Templates: {env.list_templates()}")

    # Validate existing template (should pass)
    for tpl in env.list_templates():
        gt = env.get_ground_truth(tpl)
        if gt:
            result = env.validate(tpl, gt)
            status = "✅" if result.all_passed else "❌"
            print(f"  {status} {tpl}: json={result.json_valid} sections={result.sections_valid} theme_check={result.theme_check_valid}")
            if not result.all_passed:
                print(f"     Error: {result.get_error_message()}")
