"""
Sitemuse API Validator for Horizon theme.

Validates generated templates by upserting to Shopify via Sitemuse API.
Returns binary pass/fail + error messages for OPD hint extraction.
"""

import json
import requests
from dataclasses import dataclass, field


SITEMUSE_API = "https://api.sitemuse.ai/muse/admin/liquid/theme/files/upsert"
SITEMUSE_TOKEN = "GqBOT5cvQk3S69e7KL8tjhuC1az20Hsi"
HORIZON_THEME_ID = "gid://shopify/OnlineStoreTheme/185572393248"


@dataclass
class ValidationResult:
    """Result of validating a generated template via Sitemuse API."""
    json_valid: bool = False
    json_error: str = ""
    api_valid: bool = False
    api_errors: list[str] = field(default_factory=list)
    api_raw_response: dict = field(default_factory=dict)

    @property
    def all_passed(self) -> bool:
        return self.json_valid and self.api_valid

    def to_reward_dict(self) -> dict[str, float]:
        return {
            "json_valid": 1.0 if self.json_valid else 0.0,
            "api_valid": 1.0 if self.api_valid else 0.0,
        }

    def get_error_message(self) -> str:
        """First error message — used as OPD hint."""
        if not self.json_valid:
            return f"JSON Error: {self.json_error}"
        if not self.api_valid and self.api_errors:
            return self.api_errors[0]
        return ""

    def get_all_errors(self) -> list[str]:
        """All error messages — used for multi-hint OPD."""
        errors = []
        if not self.json_valid:
            errors.append(f"JSON Error: {self.json_error}")
        errors.extend(self.api_errors)
        return errors


class SitemuseValidator:
    """
    Validates Shopify templates by upserting to Horizon theme via Sitemuse API.

    Usage:
        validator = SitemuseValidator()
        result = validator.validate("page.about", generated_json_string)
    """

    def __init__(
        self,
        api_url: str = SITEMUSE_API,
        token: str = SITEMUSE_TOKEN,
        theme_id: str = HORIZON_THEME_ID,
        timeout: int = 30,
    ):
        self.api_url = api_url
        self.token = token
        self.theme_id = theme_id
        self.timeout = timeout
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.token}",
        }

    def validate(self, template_type: str, generated_json: str) -> ValidationResult:
        """
        Validate a generated template.

        Args:
            template_type: e.g. "page.about", "collection", "index"
            generated_json: The JSON string generated by the model

        Returns:
            ValidationResult with binary pass/fail and error messages
        """
        result = ValidationResult()

        # Step 1: JSON syntax check (local, instant)
        try:
            parsed = self._parse_json(generated_json)
            result.json_valid = True
        except (json.JSONDecodeError, ValueError) as e:
            result.json_error = str(e)
            return result

        # Step 2: Shopify API validation (remote, ~200ms)
        clean_json = json.dumps(parsed)
        api_result = self._call_upsert_api(template_type, clean_json)
        result.api_valid = api_result[0]
        result.api_errors = api_result[1]
        result.api_raw_response = api_result[2]

        return result

    def _parse_json(self, json_str: str) -> dict:
        """Parse JSON, stripping leading comments if present."""
        lines = json_str.strip().split("\n")
        json_lines = []
        in_json = False
        for line in lines:
            stripped = line.strip()
            if not in_json and (stripped.startswith("{") or stripped.startswith("[")):
                in_json = True
            if in_json:
                json_lines.append(line)

        text = "\n".join(json_lines) if json_lines else json_str
        data = json.loads(text)

        if not isinstance(data, dict):
            raise ValueError("Template must be a JSON object")
        if "sections" not in data:
            raise ValueError("Template must have a 'sections' key")
        if "order" not in data:
            raise ValueError("Template must have an 'order' key")

        return data

    def _call_upsert_api(
        self, template_type: str, json_str: str
    ) -> tuple[bool, list[str], dict]:
        """
        Call Sitemuse upsert API to validate template.

        Returns:
            (passed, error_messages, raw_response)
        """
        filename = f"templates/{template_type}.json"

        payload = {
            "themeId": self.theme_id,
            "files": [{
                "filename": filename,
                "body": {
                    "type": "TEXT",
                    "value": json_str,
                },
            }],
        }

        try:
            resp = requests.post(
                self.api_url,
                headers=self.headers,
                json=payload,
                timeout=self.timeout,
            )

            if resp.status_code >= 400:
                return False, [f"API HTTP {resp.status_code}: {resp.text[:200]}"], {}

            data = resp.json()
            upsert_data = (
                data.get("data", {})
                .get("data", {})
                .get("themeFilesUpsert", {})
            )

            user_errors = upsert_data.get("userErrors", [])

            # Filter out known non-critical errors
            critical_errors = [
                err["message"]
                for err in user_errors
                if "does not refer to an existing section file" not in err.get("message", "")
            ]

            passed = len(critical_errors) == 0
            return passed, critical_errors, data

        except requests.Timeout:
            return False, ["API timeout after 30s"], {}
        except requests.RequestException as e:
            return False, [f"API error: {str(e)}"], {}

    def validate_batch(
        self, items: list[tuple[str, str]]
    ) -> list[ValidationResult]:
        """
        Validate multiple templates.

        Args:
            items: List of (template_type, generated_json) tuples

        Returns:
            List of ValidationResult
        """
        return [self.validate(tpl_type, json_str) for tpl_type, json_str in items]


# ── Reward functions for TRL GRPOTrainer ──

def sitemuse_outcome_reward(prompts, completions, **kwargs) -> list[float]:
    """Binary: API validation passes = 1, fails = 0."""
    validator = kwargs["validator"]
    template_types = kwargs["template_types"]
    responses = [c[0]["content"] for c in completions]
    return [
        1.0 if validator.validate(t, r).all_passed else 0.0
        for r, t in zip(responses, template_types)
    ]


def sitemuse_multi_reward(prompts, completions, **kwargs) -> list[float]:
    """Sum of binary rewards: json_valid + api_valid."""
    validator = kwargs["validator"]
    template_types = kwargs["template_types"]
    responses = [c[0]["content"] for c in completions]
    rewards = []
    for r, t in zip(responses, template_types):
        result = validator.validate(t, r)
        rd = result.to_reward_dict()
        rewards.append(sum(rd.values()) / len(rd))
    return rewards


def sitemuse_json_reward(prompts, completions, **kwargs) -> list[float]:
    """Binary: JSON parses correctly with required structure."""
    validator = kwargs["validator"]
    template_types = kwargs["template_types"]
    responses = [c[0]["content"] for c in completions]
    return [
        1.0 if validator.validate(t, r).json_valid else 0.0
        for r, t in zip(responses, template_types)
    ]


if __name__ == "__main__":
    # Quick test
    validator = SitemuseValidator()

    # Test with valid template
    valid_json = json.dumps({
        "sections": {
            "main": {
                "type": "main-page",
                "blocks": {
                    "heading": {
                        "type": "text",
                        "settings": {"text": "<h1>Test Page</h1>"}
                    },
                    "content": {
                        "type": "page-content",
                        "settings": {}
                    }
                },
                "block_order": ["heading", "content"],
                "settings": {}
            }
        },
        "order": ["main"]
    })

    print("Testing valid template...")
    result = validator.validate("page.rl-test-valid", valid_json)
    print(f"  JSON valid: {result.json_valid}")
    print(f"  API valid:  {result.api_valid}")
    print(f"  All passed: {result.all_passed}")
    print(f"  Errors:     {result.api_errors}")

    # Test with invalid template
    print("\nTesting invalid template...")
    invalid_json = '{"sections": {"main": {"type": "nonexistent-section"}}, "order": ["main"]}'
    result2 = validator.validate("page.rl-test-invalid", invalid_json)
    print(f"  JSON valid: {result2.json_valid}")
    print(f"  API valid:  {result2.api_valid}")
    print(f"  Errors:     {result2.api_errors}")
    print(f"  OPD hint:   {result2.get_error_message()}")
